### ISSUE TITLE
[BUG] - document-register-element import werkt niet in Safari

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-core#51]
**Omschrijf het probleem**
In vl-core zit `import 'document-register-element/pony'` / `import '/node_modules/document-register-element/build/document-register-element.js';`

Deze import geeft volgend probleem:
![image](https://user-images.githubusercontent.com/29454303/74239290-d8f78080-4cd7-11ea-83ac-1a9b8e7c82d8.png)

Het gevolg is dat onze applicatie niet laadt in Safari

**Omgeving (gelieve aan te vullen):**
 - Browser  Safari op MacOS
 - Versie 13.0.5 (15608.5.11)
 - Versie component 4.0.0

**Comment by driesva** [comment]
Ter info, wanneer de import in commentaar wordt gezet, laadt dit wel. Echter wordt de link-list zonder iconen getoond:

![image](https://user-images.githubusercontent.com/29454303/74240519-7358c380-4cda-11ea-9a77-796e48ec6b57.png)

**Comment by Pieter-Beckers** [comment]
Duplicaat: https://www.milieuinfo.be/jira/browse/UIG-518

**Comment by coemans** [comment]
@Pieter-Beckers, ter info: ik heb het issue nog even heropend, buitenstaanders hebben geen toegang tot Jira en kunnen zo ook meevolgen. Ik heb het issue gekoppeld aan #63. Het zal automatisch gesloten worden bij het sluiten van de PR.
